sudo: required
services:
- docker

script:
- docker pull nginx
- docker build -t webapp:cps847 .

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAUT5MUUJSEZ3Z6RMB"
  secret_access_key:
    secure: "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"
  region: "us-east-2"
  app: "webapp"
  env: "Webapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-317652771428"
  on:
    branch: master
